version: "3.9"

services:
  # Сервис Redis
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"

  # Сервис веб-приложения
  webapp:
    container_name: webapp
    build: src/
    env_file:
      - .env
    ports:
      - "8000:8000"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: on-failure
